compare-snap-git: try to stop when $() fails.
Change-Id: Iccec36c18869ea6b003b77afc4bff7d9b9aa7f10

diff --git a/bin/compare-snap-git b/bin/compare-snap-git
--- a/bin/compare-snap-git
+++ b/bin/compare-snap-git
@@ -63,6 +63,9 @@ extract_gitsha_rx='.*~[[:digit:]]\+\.gbp\(.*\)'
 # Extract the sha1 ... from git & from the changelog
 # set -x
 readonly pkgname=$(deb-pkg-name .)
+if [[ $? != 0 || -z "$pkgname" ]]; then
+   die "deb-pkg-name failed"
+fi
 if debian_changelog_sha=$(dpkg-query --show --showformat='${Dgit}' $pkgname)
         #expr match $changelog_version $extract_gitsha_rx
 # mmc:
