Detect failure in "Command Substitution" -- report the reason
Change-Id: I71bd1b78360e09dcb9f391763d28d3a9e7542e71

diff --git a/bin/git-compare-remote b/bin/git-compare-remote
--- a/bin/git-compare-remote
+++ b/bin/git-compare-remote
@@ -94,6 +94,9 @@ if [ $# -gt 1 ]; then
     shift
 else
     branch=$(current_branch_name)
+    if [[ $? != 0 ]]; then
+        die "not on a branch -> cannot compare"
+    fi
 fi
 
 # so the remote branch:
