git-add-remote-sibling: migrate to getopt; work with any (host)name
Change-Id: I1aa472616abc036f2b70f8b06fdd0511a925aa5a

diff --git a/bin/git-add-remote-sibling b/bin/git-add-remote-sibling
--- a/bin/git-add-remote-sibling
+++ b/bin/git-add-remote-sibling
@@ -1,4 +1,4 @@
-#!/bin/zsh -eu
+#!/usr/bin/zsh -feu
 
 # Tool to setup a mirror of git repositories in an identical dir-hierarchy (on 2 hosts).
 # This is only about SSH-based git. not git:// urls!
@@ -7,16 +7,20 @@
 # die ... maybe git-functions should source it?
 source /usr/share/mmc-shell/mmc-functions.sh
 source /usr/share/mmc-shell/git-functions.sh
-set -x
+
+unsetopt FUNCTION_ARGZERO
 usage()
 {
     cat <<EOF
 usage: ${0##*/} [+-h] [-n URL] [-d]
 -d verbose
--n ex. ${GIT_REMOTE_NAME-}
--u ex ${GIT_URL-}
+--name -n ex. ${GIT_REMOTE_NAME-}
+--url -u ex ${GIT_URL-}
 EOF
 }
+if getopt -T; then # should test (( $? = -4 ))
+    die "incompatible  getopt(1) installed. Abort"
+fi
 
 #possible wrapped into echo(1). for a dry run.
 CMD=
@@ -26,57 +30,80 @@ remote_path=$(get_remote_path)
 
 override=n
 verbose=n
-while getopts :hcdfn:u:v OPT; do
-    case $OPT in
-        c)
-            clone=y
-            ;;
-        f)
-            override=y
-            ;;
-        d)
-            # run_dry=y
-            CMD=echo
-            ;;
-        h|+h)
-            usage
-            exit 0
-            ;;
-        n|+n)
-            GIT_REMOTE_NAME=$OPTARG
-            ;;
-        u)
-            GIT_URL=$OPTARG
-            ;;
-        v)
-            verbose=y
-            ;;
-        *)
-            usage >&2
-            exit 2
-    esac
-done
-shift OPTIND-1
-OPTIND=1
 
-if [ $# -gt 0 ]; then
-    usage
-    exit 1
-fi
+# this splits, reorders,
+cmd_options=$(getopt --name $0 --shell bash \
+                     --longoptions verbose,url:,name:,dry,help \
+                     --options hcdfn:u:v -- "$@") || { usage && exit 1 }
+set -x
+# setopt KSH_ARRAYS
+eval set -- "$cmd_options"
+
+while (( $# > 0 )) do
+      echo $1 >&2
+      case $1 in
+          -c)
+              clone=y
+              ;;
+          -f)
+              override=y
+              ;;
+          -d)
+              # run_dry=y
+              CMD=echo
+              ;;
+          -h|--help)
+              usage
+              exit 0
+              ;;
+          -n|--name)
+              GIT_REMOTE_NAME=$2
+              shift
+              ;;
+          -u)
+              GIT_URL=$2
+              shift
+              ;;
+          -v)
+              verbose=y
+              ;;
+          --)
+              shift
+              break
+              ;;
+          *)
+              usage >&2
+              exit 2
+      esac
+      shift
+done
+
+# if [ $# -gt 0 ]; then
+#     usage
+#     exit 1
+# fi
 
 # set_remote_name
-guess_twin
 
-if [[ $clone = "y" ]];
-then
-    $CMD git clone $GIT_URL:$remote_path
-else
+      if [[ -n $GIT_REMOTE_NAME ]]; then
+          if [[ -z ${GIT_URL-} ]];then
+              GIT_URL=michal@$GIT_REMOTE_NAME:$(get_remote_path)
+          fi
+      else
+          guess_twin
+      fi
 
-    if [ $override = y ]; then
-        $CMD git remote set-url $GIT_REMOTE_NAME $GIT_URL:$remote_path
-    else
-        $CMD git remote add $GIT_REMOTE_NAME $GIT_URL
-    fi
 
-    git fetch $GIT_REMOTE_NAME
-fi
+      if [[ $clone = "y" ]];
+      then
+          $CMD git clone $GIT_URL:$remote_path
+      else
+
+          if [ $override = y ]; then
+              $CMD git remote set-url $GIT_REMOTE_NAME $GIT_URL:$remote_path
+          else
+              $CMD git remote add $GIT_REMOTE_NAME $GIT_URL
+          fi
+
+          git fetch $GIT_REMOTE_NAME
+      fi
