git-compare-remotes: simplify, clean
Change-Id: Ie5457179d488d980ce888149b7b0eaa3ef275911

diff --git a/bin/git-compare-remotes b/bin/git-compare-remotes
--- a/bin/git-compare-remotes
+++ b/bin/git-compare-remotes
@@ -6,32 +6,41 @@ usage()
 {
     setopt POSIX_ARGZERO
     cat <<EOF
-usage: ${0##*/} [+-h] [-q] [--]  branch remote
+usage: ${0##*/} [+-h] [-q] [--] [remote] [branch]
+
+remote is by default the "favourite" one.
 -q  don't dump the commits
 
 EOF
 }
 
+
+# Given 2 commits as parameters ... look at the lattice
 # return 1 if A < B
 # 0 if  A=B
 # 1 less
 # 2 more
 # 3  incomparable
-#
 # 4 error?
+
+#  uses $verbose
 compare_commits()
 {
-    local first=$(git log $1 --max-count=1 --format="%H")
-    local second=$(git log $2 --max-count=1 --format="%H")
-    if [ -z "$first" -o -z "$second" ]; then
-        if [ $verbose = y ]; then echo "$first $second" >&2;fi
+    # the sha?
+    # $(git rev-parse $1)
+    # local
+    readonly first=$(git log $1 --max-count=1 --format="%H")
+    readonly second=$(git log $2 --max-count=1 --format="%H")
+
+    if [[ -z "$first" -o -z "$second" ]]; then
+        if [[ $verbose = y ]]; then echo "$first $second" >&2;fi
         return 4
     fi
-    if [ $first = $second ]; then
+    if [[ $first = $second ]]; then
         return 0;
     fi
 
-    common=$(git merge-base $1 $2)
+    readonly common=$(git merge-base $first $second)
     if [ $? != 0 ]; then
         if [ $verbose = y ]; then echo "no common merge-base">&2;fi
         return 4;
@@ -66,6 +75,7 @@ done
 shift OPTIND-1
 OPTIND=1
 
+# the remote:
 set_remote_name
 
 if [ $# -gt 1 ]; then
@@ -73,6 +83,7 @@ if [ $# -gt 1 ]; then
     shift
 fi
 
+# the branch
 if [ $# -gt 1 ]; then
     branch=$1
     shift
@@ -80,31 +91,16 @@ else
     branch=$(current_branch_name)
 fi
 
+# so the remote branch:
 REMOTE=remotes/$GIT_REMOTE_NAME/$branch
 
-set +e
-# could compare with FETCH_HEAD
-compare_commits $branch $REMOTE;
+
+# I need the exit status, and it won't be zero:
+(set +e
+ # could compare with FETCH_HEAD
+ compare_commits $branch $REMOTE
+ )
 cmp=$?
-set -e
-
-
-# # fixme: from where I have just fetched!
-
-# remotes=$(git remote)
-# if [ ${#remotes} = 1 ]
-# then
-#     REMOTE=remotes/${remotes[1]}/master
-# elif git_ref_exists remotes/origin/master;
-# then
-#     REMOTE=remotes/origin/master
-# elif git_ref_exists remotes/maruska/master
-# then
-#     REMOTE=remotes/maruska/master
-# else
-#     REMOTE=remotes/m/master
-# fi
-# # REMOTE=FETCH_HEAD
 
 
 args=(--max-count 15)
