rebase-segment:
push the "Start" only on completion. Still improvement todo.
don't use git-rebase-branch. (in fact, now useless?)
Use GIT_DIR

Change-Id: Ibafc50e94672d131100891027f0da911c560b0a7

diff --git a/bin/git-rebase-segment b/bin/git-rebase-segment
--- a/bin/git-rebase-segment
+++ b/bin/git-rebase-segment
@@ -1,16 +1,44 @@
 #! /usr/bin/zsh -feu
 
 
-br=$1
-start="start/$br"
-base="base/$br"
+GIT_DIR=$(git rev-parse --show-toplevel)
+
+usage()
+{
+    print "usage: ${0##*/} [--] ARGS..."
+}
+
+while getopts :h OPT; do
+    case $OPT in
+	h)
+	    usage
+	    exit 0
+	    ;;
+	*)
+	    print "usage: ${0##*/} [--] ARGS..."
+	    exit 2
+    esac
+done
+shift OPTIND-1
+OPTIND=1
+
+
+branch=$1
+
+start="start/$branch"
+base="base/$branch"
 # base=
 # base/mmc-atkbd
 
-git-rebase-branch $br $start $base
 
-# wrong?
-newstart=$(git show-ref --hash $base)
+# This might fail. in that case:
+# 1/ save the state, to reinvoke later:
+if git rebase --onto $base $start $branch;
+then
+   # wrong?
+    newstart=$(git show-ref --hash $base)
 
-echo $newstart >! .git/refs/start/$br
-# echo $(git rev-ref $base) > .git/refs/start/$br
+    echo $newstart >! $GIT_DIR/.git/refs/start/$branch
+    # echo $(git rev-ref $base) > .git/refs/start/$br
+fi
+
