Exit on any failure
Change-Id: Ie65591ae2176ee357586457531a4aab40ea62c22

diff --git a/bin/repo_restore_horizon b/bin/repo_restore_horizon
--- a/bin/repo_restore_horizon
+++ b/bin/repo_restore_horizon
@@ -26,7 +26,8 @@ compare_horizons()
 	then
 	    cat
 	else
-	    awk '/^(.*)\s(.*)$/  {system(sprintf("git-restate %s  %s", $1, $2));}'
+	    # fixme: failure of `system' won't exit the awk!
+	    awk '/^(.*)\s(.*)$/  {if (system(sprintf("git-restate %s  %s", $1, $2)) != 0);{ exit 1}; }'
 	fi
     )
 # join -t '\t' -v 1 $1 $2
