Keep the full horizont as a version-of-day.
The file, after applying rebase over 'repo sync'
will remain and can be used as a base identified
by the date.

Build version can use it. "MM-DD-pr1-sha1-pro2-sha1 ..."

So, repo-sync invokes new apis.

Done:
 repo-save-head outputs:

dir
sha [[ref] stash-sha]

This is then processed by repo_extract_symbolic.awk

repo-save-head adapted to work with that format.

Change-Id: I93e2f4753cf1a2c39321cd733072c87d408a3828

diff --git a/bin/repo-save-head b/bin/repo-save-head
--- a/bin/repo-save-head
+++ b/bin/repo-save-head
@@ -1,9 +1,19 @@
 #!/usr/bin/zsh -feu
 
-# output the HEAD sha. possibly also a stash SHA1
+# output:
+# --------------
+# dir
+# sha [ref] [stash]
+#-------------
+# the HEAD ref (either sha or symbolic ref).
+# Possibly also a stash SHA1 --
+# git stash -- "No local changes to save" does nothing then.
 # git-reset, unless
 
+# create stash too.
 stash=y
+
+# reset/clean the git repo:
 reset=y
 
 # git stash -m "pre-repo-sync"
@@ -29,13 +39,33 @@ done
 shift OPTIND-1
 OPTIND=1
 
-
+# ====
 pwd
-echo -n "$(cat .git/HEAD)"
+
+
+# fixme:
+symbolic=$(cat .git/HEAD)
+sha=$(git rev-parse HEAD)
+echo -n "$sha"
+
+set +e
+#=$(expr match "$symbolic"  '^(rev: .+)$')
+matched=$(expr match "$symbolic"  '^ref: .*$')
+#&> /dev/null
+# res=$?
+if [ $matched -gt 1 ]; then
+    echo -n  "\t$symbolic"; #${a#ref: };
+else
+    :
+fi
+set -e
+
+
 
 if test $stash = y;
 then
     msg="pre repo-sync $(date +%m-%d)"
+    # fixme: what if this fails?
     sha=$(git stash create "$msg")
 
     if [ -n "$sha" ];
