rsync-from-me: use die to print usage.
Change-Id: I80fd72097261d0b7964ae2eefc683eae4dc9b6a4

diff --git a/bin/rsync-from-me b/bin/rsync-from-me
--- a/bin/rsync-from-me
+++ b/bin/rsync-from-me
@@ -56,6 +56,7 @@
 die()
 {
     echo $@ >&2
+    usage >&2
     exit 1;
 }
 
@@ -90,32 +91,23 @@ EOF
 
 
 if getopt -T; then # should test (( $? = -4 ))
-    echo "incompatible  getopt(1) installed. Abort"
-
-    usage >&2
-    exit -1
+    die "incompatible  getopt(1) installed. Abort"
 fi
 
 
 
 if ! [ -e .rsync.env -a -e .rsync-ignore ]; then
-    echo "missing .rsync.env (or .rsync-ignore) file in $(pwd)" >&2
-    usage >&2
-    exit 1
+    die "missing .rsync.env (or .rsync-ignore) file in $(pwd)"
 fi
 
 source .rsync.env
 
 # sanity check:
 if [ -z "${SOURCE_REPO-}" ]; then
-    echo "the env file does not define the SOURCE_REPO" >&2
-    usage >&2
-    exit 1
+    die "the env file does not define the SOURCE_REPO"
 fi
 if [ -z "${RSYNC_RULES-}" ]; then
-    echo "the env file does not define the RSYNC_RULES" >&2
-    usage >&2
-    exit 1
+    die "the env file does not define the RSYNC_RULES"
 fi
 
 
